### ISSUE TITLE
Question regarding social image

### ISSUE THREAD

**Issue by miklereverie** [mhyfritz/astro-landing-page#18]
This might not be an issue but a problem on my end, I've changed the social image to a new one, rebuilt the project and uploaded to netlify, but the old one is still showing up. Am I forgetting to change some configuration on the template?

![image](https://github.com/user-attachments/assets/71ffe447-3007-4d9d-9cb1-4b941e04e627)

**Comment by mhyfritz** [comment]
Did you edit `astro.config.mjs`? https://github.com/mhyfritz/astro-landing-page/blob/7fc9b493a273258ee0b4da5cac2f3b66f0bfd5e8/astro.config.mjs#L7

The image URL is constructed using this value as the base path: https://github.com/mhyfritz/astro-landing-page/blob/7fc9b493a273258ee0b4da5cac2f3b66f0bfd5e8/src/pages/index.astro#L13

Hope that help!

**Comment by miklereverie** [comment]
The change in astro.config.mjs is what was missing! Thank you so much! That fixed it.
