### ISSUE TITLE
Light Theme menu isn't visible on mobile devices

### ISSUE THREAD

**Issue by DenjixPochita** [mhyfritz/astro-landing-page#2]
## Steps to reproduce:
- Switch to mobile emulator on browser
- Scroll down and switch dark theme to white theme
- Scroll on top and go to mobile menu
## Expected: Visible text
----
## Screenshot
![astro-moon-landing netlify app](https://user-images.githubusercontent.com/96773885/189274483-4cb650c0-5cba-412c-aa3a-9429831db8cf.png)

**Comment by mhyfritz** [comment]
Hey @DenjixPochita! Thanks for the detailed bug report. This should be fixed now!
