### ISSUE TITLE
Usage of the template

### ISSUE THREAD

**Issue by lauhon** [mhyfritz/astro-landing-page#3]
Hi there,

I really love this as a starter for portfolios.

When I first found it on the Astro Page, I was a bit confused about how to use it. I basically found this repo on accident when googling "astro moon landing github".

Maybe even more people would love to use this template if there is not "only" a link to the astro github, but also to this repository.

I realize there is a chance that there is an easy-to-find link to this somewhere in the documentation, but at least I didnt find it :D

**Comment by peterhijma** [comment]
Totally agree! I guess the GitHub icon link at the bottom should point to this repo, instead of astro itself?

**Comment by mhyfritz** [comment]
Hi @lauhon. Thanks for raising this issue and glad the template is helpful!

The GitHub link was actually shown until very recently on https://astro.build/themes/, seems this was changed...
In any case, it's a good idea to link to the repo, so I added a [GitHub Corner](https://tholman.com/github-corners/) and also changed the footer link as suggested by @peterhijma.
