### ISSUE TITLE
Illegal hardware instruction (core dumped)  pnpm dev

### ISSUE THREAD

**Issue by seokkuuu** [mhyfritz/astro-landing-page#6]
## Problem

I've clonned the repo, of course, I ran `pnpm install` but when I run the project with `pnpm dev` or `pnpm run dev` it throws an error.

## Output

```
> astro-landing-page@0.0.1 dev /path/to/my/dev/dir/astro-landing-page
> astro dev

[1]    11789 illegal hardware instruction (core dumped)  pnpm dev
```

I don't know what is happening. :(

I tried using `npm` or `yarn`, but the same...

**Comment by mhyfritz** [comment]
Possibly a Node.js issue. I would try different versions of Node. You can easily do this with [nvm](https://github.com/nvm-sh/nvm). Make sure to delete `node_modules` and then run `npm install` again. Hope that helps!

**Comment by mhyfritz** [comment]
Closing this now. Feel free to re-open if you have any update.
