### ISSUE TITLE
Issue with animated star background

### ISSUE THREAD

**Issue by reveurguy** [mhyfritz/astro-landing-page#7]
Hii. I am trying to use the animated starfield background for hero section in my project. I am using Next.js and Typescript.
The code worked fine initially , but after sometime it is not running at all and also while it was working in development, it didn't worked in production as i deployed the site.
If i delete the node_modules and .next folders and run in development, the background works fine for sometime, then after that again stops working and not at all working in production.
I have the code in the script tag (in your code) in a separate ts file and have imported that in a tsx file which has the div and canvas code.
Can you think of any reason why the issue is occuring, there are no errors or logs in the console as well.

**Comment by mhyfritz** [comment]
No idea, sorry! Probably some issue with how you are integrating my canvas code in Next/React, but otherwise I really do not know what's happening.

**Comment by mhyfritz** [comment]
Will close this now. Feel free to re-open if you have any update!
